export const ADD_QUESTION = 'ADD_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const ADD_ANSWER = 'ADD_ANSWER';
export const DELETE_ANSWER = 'DELETE_ANSWER';
export const ADD_RADIO_ANSWER = 'ADD_RADIO_ANSWER';
export const ADD_LIST_ANSWER = 'ADD_LIST_ANSWER';